# Generated by Django 6.0.1 on 2026-07-09 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lehrplan', '0013_alter_ausbildungseinheit_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=250, verbose_name='Thema')),
                ('inhalt', models.CharField(default='?', max_length=50, verbose_name='Überschrift')),
                ('frage', models.TextField(verbose_name='Frage')),
                ('musterantwort', models.TextField(default='', verbose_name='Musterantwort')),
                ('bild', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bild')),
                ('bildmuster', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bild Muster')),
                ('bildbreite', models.IntegerField(default=80, verbose_name='Bildbreite in %')),
                ('punkte', models.IntegerField(default=1, verbose_name='Erreichbare Punkte')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('thema', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lehrplan.ausbildungseinheit', verbose_name='Ausbildungseinheit')),
            ],
            options={
                'verbose_name': 'Frage',
                'verbose_name_plural': 'Fragen',
                'ordering': ['thema', 'titel'],
            },
        ),
    ]
