# Generated by Django 6.0.1 on 2026-08-31 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kklausur', '0001_initial'),
        ('lehrplan', '0016_alter_ausbildungseinheit_kuerzel'),
        ('stammdaten', '0017_alter_abwesendma_daytime_alter_jourfixe_daytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klausur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Überschrift')),
                ('datum', models.DateTimeField(verbose_name='Termin')),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.gruppe', verbose_name='Gruppe')),
                ('thema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lehrplan.ausbildungseinheit', verbose_name='Thema')),
            ],
            options={
                'verbose_name': 'Klausur',
                'verbose_name_plural': 'Klausuren',
            },
        ),
    ]
