# Generated by Django 6.0.1 on 2026-08-31 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kklausur', '0002_klausur'),
    ]

    operations = [
        migrations.AddField(
            model_name='klausur',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Kommentar'),
        ),
        migrations.CreateModel(
            name='KlausurFrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
                ('startnp', models.BooleanField(default=False, verbose_name='Start mit neuer Seite')),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kklausur.frage', verbose_name='Frage')),
                ('klausur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kklausur.klausur', verbose_name='Klausur')),
            ],
            options={
                'verbose_name': 'KlausurFrage',
                'verbose_name_plural': 'KlausurFrage',
            },
        ),
    ]
