# Generated by Django 6.0.1 on 2026-08-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kklausur', '0003_klausur_comment_klausurfrage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klausur',
            options={'ordering': ['gruppe', '-datum'], 'verbose_name': 'Klausur', 'verbose_name_plural': 'Klausuren'},
        ),
        migrations.AlterModelOptions(
            name='klausurfrage',
            options={'ordering': ['klausur', 'position'], 'verbose_name': 'KlausurFrage', 'verbose_name_plural': 'KlausurFrage'},
        ),
        migrations.AddField(
            model_name='klausur',
            name='erledigt',
            field=models.BooleanField(default=False, verbose_name='abgeschlossen'),
        ),
    ]
