# Generated by Django 6.0.1 on 2026-07-06 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stammdaten', '0017_alter_abwesendma_daytime_alter_jourfixe_daytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='tn_fa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True, verbose_name='Datum')),
                ('status', models.IntegerField(verbose_name='Status')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Kommentar')),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.teilnehmer', verbose_name='Teilnehmer')),
            ],
            options={
                'verbose_name': 'Teilnehmer Frage/Anwort',
                'verbose_name_plural': 'Teilnehmer Fragen/Anworten',
            },
        ),
    ]
