# Generated by Django 6.0.1 on 2026-07-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frageantwort', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tn_fa',
            options={'ordering': ['-datum'], 'verbose_name': 'Teilnehmer Frage/Anwort', 'verbose_name_plural': 'Teilnehmer Fragen/Anworten'},
        ),
    ]
