# Generated by Django 6.0.1 on 2026-02-16 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stammdaten', '0010_alter_laptoptn_ruecknahme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daytime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=2, verbose_name='Kürzel')),
                ('long', models.CharField(max_length=50, verbose_name='Langversion')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Tageszeit',
                'verbose_name_plural': 'Tageszeiten',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('content', models.CharField(blank=True, max_length=50, null=True, verbose_name='Info')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.gruppe', verbose_name='Gruppe')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stammdaten.ausbilder', verbose_name='Ausbilder')),
                ('daytime', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ausbildungsplan.daytime', verbose_name='Tageszeit')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blöcke',
                'ordering': ['group', 'date', 'daytime'],
            },
        ),
    ]
