# Generated by Django 6.0.1 on 2026-03-02 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausbildungsplan', '0001_initial'),
        ('lehrplan', '0007_alter_fachrichtung_options_alter_lerneinheit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='lerneinheit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lehrplan.lerneinheit', verbose_name='Lerneinheit'),
        ),
    ]
