# Generated by Django 6.0.1 on 2026-07-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausbildungsplan', '0002_block_lerneinheit'),
        ('lehrplan', '0013_alter_ausbildungseinheit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='lerneinheit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lehrplan.lerneinheit', verbose_name='Ausbildungseinheit'),
        ),
    ]
