# Generated by Django 6.0.1 on 2026-07-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ausbildungsplan', '0004_alter_block_lerneinheit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='lerneinheit',
        ),
    ]
