# Generated by Django 6.0.1 on 2026-03-07 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lehrplan', '0007_alter_fachrichtung_options_alter_lerneinheit_options_and_more'),
        ('stammdaten', '0017_alter_abwesendma_daytime_alter_jourfixe_daytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage', models.TextField(verbose_name='Frage')),
                ('antwort', models.TextField(verbose_name='Musterantwort')),
                ('bild', models.ImageField(blank=True, null=True, upload_to='kimage', verbose_name='Abbildung')),
                ('punkte', models.IntegerField(default=1, verbose_name='Anzahl Punkte')),
                ('thema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lehrplan.thema', verbose_name='Thema')),
            ],
            options={
                'verbose_name': 'Frage',
                'verbose_name_plural': 'Frages',
            },
        ),
        migrations.CreateModel(
            name='Klausur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Überschrift')),
                ('zeitpunkt', models.DateTimeField(verbose_name='Zeitpunkt')),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.gruppe', verbose_name='Gruppe')),
                ('thema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lehrplan.thema', verbose_name='Thema')),
            ],
            options={
                'verbose_name': 'Klausur',
                'verbose_name_plural': 'Klausuren',
            },
        ),
    ]
