# Generated by Django 6.0.1 on 2026-03-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klausur',
            name='gruppe',
        ),
        migrations.RemoveField(
            model_name='klausur',
            name='thema',
        ),
        migrations.DeleteModel(
            name='Frage',
        ),
        migrations.DeleteModel(
            name='Klausur',
        ),
    ]
