# Generated by Django 6.0.1 on 2026-09-28 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stammdaten', '0018_alter_teilnehmer_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schrank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50, unique=True, verbose_name='Bezeichnung')),
                ('hoehe', models.IntegerField(verbose_name='Anzahl Höhe')),
                ('breite', models.IntegerField(verbose_name='Breite')),
                ('start', models.IntegerField(verbose_name='Start')),
            ],
            options={
                'verbose_name': 'Schrank',
                'verbose_name_plural': 'Schränke',
            },
        ),
        migrations.CreateModel(
            name='Fach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.IntegerField(unique=True, verbose_name='Fachnummer')),
                ('belegtbis', models.DateField(verbose_name='belegt bis:')),
                ('eingetragenam', models.DateTimeField(auto_now_add=True, verbose_name='eingetragen am')),
                ('eingetragenvon', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stammdaten.ausbilder', verbose_name='eingetragen von')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stammdaten.teilnehmer', verbose_name='Benutzer')),
                ('schrank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faecher.schrank', verbose_name='Schrank')),
            ],
            options={
                'verbose_name': 'Fach',
                'verbose_name_plural': 'Fächer',
            },
        ),
    ]
