# Generated by Django 6.0.1 on 2026-09-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faecher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fach',
            old_name='nummer',
            new_name='number',
        ),
    ]
