# Generated by Django 6.0.1 on 2026-01-14 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausbilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=10, verbose_name='Kürzel')),
                ('activ', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('bg_color', models.CharField(default='DodgerBlue', max_length=50, verbose_name='Hintergrundfarbe')),
                ('fg_color', models.CharField(default='white', max_length=50, verbose_name='Schriftfarbe')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Kommentar')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='SystemUser')),
            ],
            options={
                'verbose_name': 'Ausbilder',
                'verbose_name_plural': 'Ausbilder',
            },
        ),
    ]
