# Generated by Django 6.0.1 on 2026-01-31 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beruf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=10, verbose_name='Kürzel')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('activ', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Beruf',
                'verbose_name_plural': 'Berufe',
                'ordering': ['short'],
            },
        ),
        migrations.CreateModel(
            name='Raum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=10, verbose_name='Bezeichnung')),
                ('info', models.TextField(verbose_name='Info')),
                ('row', models.IntegerField(default=1, verbose_name='Reihen')),
                ('col', models.IntegerField(default=1, verbose_name='Spalten')),
            ],
            options={
                'verbose_name': 'Raum',
                'verbose_name_plural': 'Räume',
            },
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=10, verbose_name='Kürzel')),
                ('ort', models.CharField(max_length=50, verbose_name='Ort')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('activ', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Standort',
                'verbose_name_plural': 'Standorte',
            },
        ),
        migrations.CreateModel(
            name='Ausbilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=10, verbose_name='Kürzel')),
                ('activ', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('bg_color', models.CharField(default='DodgerBlue', max_length=50, verbose_name='Hintergrundfarbe')),
                ('fg_color', models.CharField(default='white', max_length=50, verbose_name='Schriftfarbe')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Kommentar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='SystemUser')),
            ],
            options={
                'verbose_name': 'Ausbilder',
                'verbose_name_plural': 'Ausbilder',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('short', models.CharField(max_length=10, verbose_name='Kürzel')),
                ('activ', models.BooleanField(default=True, verbose_name='aktiv')),
                ('aubi', models.ManyToManyField(to='stammdaten.ausbilder', verbose_name='Ausbilder')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Teamleiter', to='stammdaten.ausbilder', verbose_name='Teamleiter')),
                ('standort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.standort', verbose_name='Standort')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('short', models.CharField(max_length=10, verbose_name='Kürzel')),
                ('activ', models.BooleanField(default=True, verbose_name='aktiv')),
                ('raum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='stammdaten.raum', verbose_name='Raum')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stammdaten.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Gruppe',
                'verbose_name_plural': 'Gruppen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('activ', models.BooleanField(default=True, verbose_name='aktiv')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.gruppe', verbose_name='Gruppe')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stammdaten.beruf', verbose_name='Beruf')),
            ],
            options={
                'verbose_name': 'Teilnehmer',
                'verbose_name_plural': 'Teilnehmer',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.AddField(
            model_name='gruppe',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stammdaten.teilnehmer', verbose_name='Gruppensprecher'),
        ),
        migrations.CreateModel(
            name='TNAnmerkung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Datum')),
                ('comment', models.TextField(verbose_name='Anmerkung')),
                ('ausbilder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.ausbilder', verbose_name='Ausbilder')),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.teilnehmer', verbose_name='Teilnehmer')),
            ],
            options={
                'verbose_name': 'TNAnmerkung',
                'verbose_name_plural': 'TNAnmerkungen',
                'ordering': ['-date'],
            },
        ),
    ]
