# Generated by Django 6.0.1 on 2026-01-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=10, verbose_name='Kürzel')),
                ('ort', models.CharField(max_length=50, verbose_name='Ort')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('activ', models.BooleanField(verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Standort',
                'verbose_name_plural': 'Standorte',
            },
        ),
    ]
