# Generated by Django 6.0.1 on 2026-01-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raum',
            name='gang',
            field=models.IntegerField(default=3, verbose_name='Gang'),
        ),
        migrations.AlterField(
            model_name='raum',
            name='col',
            field=models.IntegerField(default=6, verbose_name='Spalten'),
        ),
        migrations.AlterField(
            model_name='raum',
            name='row',
            field=models.IntegerField(default=5, verbose_name='Reihen'),
        ),
    ]
