# Generated by Django 6.0.1 on 2026-01-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0002_standort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standort',
            name='activ',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
