# Generated by Django 6.0.1 on 2026-02-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0002_raum_gang_alter_raum_col_alter_raum_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnehmer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Bild'),
        ),
    ]
