# Generated by Django 6.0.1 on 2026-02-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0004_alter_teilnehmer_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teilnehmer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='stammdaten/<django.db.models.fields.related.ForeignKey>', verbose_name='Bild'),
        ),
    ]
