# Generated by Django 6.0.1 on 2026-01-14 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0004_alter_ausbilder_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('short', models.CharField(max_length=10, verbose_name='Kürzel')),
                ('activ', models.BinaryField(default=True, verbose_name='aktiv')),
                ('aubi', models.ManyToManyField(to='stammdaten.ausbilder', verbose_name='Ausbilder')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Teamleiter', to='stammdaten.ausbilder', verbose_name='Teamleiter')),
                ('standort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.standort', verbose_name='Standort')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
