# Generated by Django 6.0.1 on 2026-01-14 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0005_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Teamleiter', to='stammdaten.ausbilder', verbose_name='Teamleiter'),
        ),
    ]
