# Generated by Django 6.0.1 on 2026-01-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0006_alter_team_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='activ',
            field=models.BinaryField(verbose_name='aktiv'),
        ),
    ]
