# Generated by Django 6.0.1 on 2026-02-16 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0006_alter_teilnehmer_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopTN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Laptop Nummmer')),
                ('ausgabe', models.DateField(verbose_name='Ausgabe')),
                ('rueckname', models.DateField(blank=True, null=True, verbose_name='Rückname')),
                ('ausgabevon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ausbilderausg', to='stammdaten.ausbilder', verbose_name='Ausgegeben von')),
                ('ruecknamevon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ausbilderrueck', to='stammdaten.ausbilder', verbose_name='zurück genommen von')),
                ('tn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.teilnehmer', verbose_name='Teilnehmer')),
            ],
            options={
                'verbose_name': 'Teilnehmer Laptop',
                'verbose_name_plural': 'Teilnehmer Laptops',
                'ordering': ['tn', '-ausgabe'],
            },
        ),
    ]
