# Generated by Django 6.0.1 on 2026-02-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0007_laptoptn'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptoptn',
            name='anmerkung',
            field=models.TextField(blank=True, null=True, verbose_name='Anmerkung'),
        ),
    ]
