# Generated by Django 6.0.1 on 2026-02-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0008_laptoptn_anmerkung'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teilnehmer',
            options={'ordering': ['name'], 'verbose_name': 'Teilnehmer', 'verbose_name_plural': 'Teilnehmer'},
        ),
        migrations.RenameField(
            model_name='laptoptn',
            old_name='rueckname',
            new_name='ruecknahme',
        ),
        migrations.RenameField(
            model_name='laptoptn',
            old_name='ruecknamevon',
            new_name='ruecknahmevon',
        ),
        migrations.AlterField(
            model_name='laptoptn',
            name='ausgabe',
            field=models.DateField(blank=True, null=True, verbose_name='Ausgabe'),
        ),
    ]
