# Generated by Django 6.0.1 on 2026-01-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0008_alter_team_activ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='activ',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
    ]
