# Generated by Django 6.0.1 on 2026-02-16 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0009_alter_teilnehmer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptoptn',
            name='ruecknahme',
            field=models.DateField(blank=True, null=True, verbose_name='Rücknahme'),
        ),
        migrations.AlterField(
            model_name='laptoptn',
            name='ruecknahmevon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ausbilderrueck', to='stammdaten.ausbilder', verbose_name='zurückgenommen von'),
        ),
    ]
