# Generated by Django 6.0.1 on 2026-01-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0009_alter_team_activ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beruf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=10, verbose_name='Kürzel')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('activ', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Beruf',
                'verbose_name_plural': 'Berufe',
            },
        ),
    ]
