# Generated by Django 6.0.1 on 2026-01-14 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0010_beruf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('short', models.CharField(max_length=10, verbose_name='Kürzel')),
                ('activ', models.BooleanField(default=True, verbose_name='aktiv')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stammdaten.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Gruppe',
                'verbose_name_plural': 'Gruppen',
            },
        ),
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activ', models.BooleanField(default=True, verbose_name='aktiv')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stammdaten.gruppe', verbose_name='Gruppe')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stammdaten.beruf', verbose_name='Beruf')),
            ],
            options={
                'verbose_name': 'Teilnehmer',
                'verbose_name_plural': 'Teilnehmer',
            },
        ),
        migrations.AddField(
            model_name='gruppe',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stammdaten.teilnehmer', verbose_name='Gruppensprecher'),
        ),
    ]
