# Generated by Django 6.0.1 on 2026-02-23 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0010_alter_laptoptn_ruecknahme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbwesendMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Datum')),
                ('day', models.IntegerField(blank=True, choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag')], null=True, verbose_name='Wochentag entweder)')),
                ('daytime', models.CharField(choices=[('gt', 'Ganztag'), ('am', 'Vormittag'), ('pm', 'Nachmittag')], default='gt', max_length=2, verbose_name='Tageszeit oder')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Kommentar')),
                ('aubi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.ausbilder', verbose_name='Ausbilder')),
            ],
            options={
                'verbose_name': 'AubiBlock',
                'verbose_name_plural': 'AubiBlocks',
            },
        ),
    ]
