# Generated by Django 6.0.1 on 2026-02-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0011_abwesendma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abwesendma',
            options={'ordering': ['-date'], 'verbose_name': 'AubiBlock', 'verbose_name_plural': 'AubiBlocks'},
        ),
        migrations.AlterField(
            model_name='abwesendma',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum     entweder'),
        ),
        migrations.AlterField(
            model_name='abwesendma',
            name='day',
            field=models.IntegerField(blank=True, choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag')], null=True, verbose_name='Wochentag oder    '),
        ),
    ]
