# Generated by Django 6.0.1 on 2026-01-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0011_gruppe_teilnehmer_gruppe_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnehmer',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
