# Generated by Django 6.0.1 on 2026-02-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0012_alter_abwesendma_options_alter_abwesendma_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abwesendma',
            options={'ordering': ['-date'], 'verbose_name': 'Abwesenheit Mitarbeiter', 'verbose_name_plural': 'Abwesenheiten Mitarbeiter'},
        ),
    ]
