# Generated by Django 6.0.1 on 2026-01-14 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0012_teilnehmer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teilnehmer',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.gruppe', verbose_name='Gruppe'),
        ),
    ]
