# Generated by Django 6.0.1 on 2026-03-03 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0013_alter_abwesendma_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jourfixe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('datetime', models.CharField(choices=[('gt', 'Ganztag'), ('am', 'Vormittag'), ('pm', 'Nachmittag')], max_length=2, verbose_name='Tageszeit')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Info')),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.gruppe', verbose_name='Gruppe')),
            ],
            options={
                'verbose_name': 'Termin Jour Fixe',
                'verbose_name_plural': 'Termine Jour Fixe',
            },
        ),
    ]
