# Generated by Django 6.0.1 on 2026-01-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0013_alter_teilnehmer_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teilnehmer',
            old_name='group',
            new_name='tn_group',
        ),
    ]
