# Generated by Django 6.0.1 on 2026-01-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0014_rename_group_teilnehmer_tn_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teilnehmer',
            old_name='tn_group',
            new_name='group',
        ),
    ]
