# Generated by Django 6.0.1 on 2026-03-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0014_jourfixe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abwesendma',
            name='daytime',
            field=models.CharField(choices=[('am', 'Vormittag'), ('pm', 'Nachmittag')], default='gt', max_length=2, verbose_name='Tageszeit oder'),
        ),
    ]
