# Generated by Django 6.0.1 on 2026-01-15 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0015_rename_tn_group_teilnehmer_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beruf',
            options={'ordering': ['short'], 'verbose_name': 'Beruf', 'verbose_name_plural': 'Berufe'},
        ),
        migrations.AlterModelOptions(
            name='gruppe',
            options={'ordering': ['name'], 'verbose_name': 'Gruppe', 'verbose_name_plural': 'Gruppen'},
        ),
        migrations.AlterModelOptions(
            name='teilnehmer',
            options={'ordering': ['group', 'name'], 'verbose_name': 'Teilnehmer', 'verbose_name_plural': 'Teilnehmer'},
        ),
        migrations.CreateModel(
            name='TNAnmerkung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Datum')),
                ('comment', models.TextField(verbose_name='Anmerkung')),
                ('ausbilder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.ausbilder', verbose_name='Ausbilder')),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.teilnehmer', verbose_name='Teilnehmer')),
            ],
            options={
                'verbose_name': 'TNAnmerkung',
                'verbose_name_plural': 'TNAnmerkungen',
            },
        ),
    ]
