# Generated by Django 6.0.1 on 2026-03-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0015_alter_abwesendma_daytime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jourfixe',
            old_name='datetime',
            new_name='daytime',
        ),
    ]
