# Generated by Django 6.0.1 on 2026-03-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0016_rename_datetime_jourfixe_daytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abwesendma',
            name='daytime',
            field=models.CharField(choices=[('gt', 'Ganztag'), ('am', 'Vormittag'), ('pm', 'Nachmittag')], default='gt', max_length=2, verbose_name='Tageszeit oder'),
        ),
        migrations.AlterField(
            model_name='jourfixe',
            name='daytime',
            field=models.CharField(choices=[('vm', 'Vormittag'), ('nm', 'Nachmittag')], max_length=2, verbose_name='Tageszeit'),
        ),
    ]
