# Generated by Django 6.0.1 on 2026-01-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0016_alter_beruf_options_alter_gruppe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tnanmerkung',
            options={'ordering': ['-date'], 'verbose_name': 'TNAnmerkung', 'verbose_name_plural': 'TNAnmerkungen'},
        ),
    ]
