# Generated by Django 6.0.1 on 2026-01-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0017_alter_tnanmerkung_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=10, verbose_name='Bezeichnung')),
                ('info', models.TextField(verbose_name='Info')),
            ],
            options={
                'verbose_name': 'Raum',
                'verbose_name_plural': 'Räume',
            },
        ),
    ]
