# Generated by Django 6.0.1 on 2026-01-30 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0018_raum'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruppe',
            name='raum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='stammdaten.raum', verbose_name='Raum'),
            preserve_default=False,
        ),
    ]
