# Generated by Django 6.0.1 on 2026-01-30 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0019_gruppe_raum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruppe',
            name='raum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='stammdaten.raum', verbose_name='Raum'),
        ),
    ]
