# Generated by Django 6.0.1 on 2026-01-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0020_alter_gruppe_raum'),
    ]

    operations = [
        migrations.AddField(
            model_name='raum',
            name='col',
            field=models.IntegerField(default=1, verbose_name='Spalten'),
        ),
        migrations.AddField(
            model_name='raum',
            name='row',
            field=models.IntegerField(default=1, verbose_name='Reihen'),
        ),
    ]
