# Generated by Django 6.0.1 on 2026-01-31 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stammdaten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TNAnwesend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True, verbose_name='Datum')),
                ('anwesend', models.BooleanField(verbose_name='Anwesend')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Kommentar')),
                ('ausbilder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.ausbilder', verbose_name='Ausbilder')),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.teilnehmer', verbose_name='Teilnehmer')),
            ],
            options={
                'verbose_name': 'Teilnehmer Anwesenheit',
                'verbose_name_plural': 'Teilnehmer Anwesenheiten',
                'ordering': ['teilnehmer', '-datum'],
            },
        ),
    ]
