# Generated by Django 6.0.1 on 2026-01-31 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anwesenheit', '0001_initial'),
        ('stammdaten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitzplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField(verbose_name='Spalte')),
                ('row', models.IntegerField(verbose_name='Reihe')),
                ('raum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.raum', verbose_name='Raum')),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.teilnehmer', verbose_name='Teilnehmer')),
            ],
            options={
                'verbose_name': 'Sitzplan',
                'verbose_name_plural': 'Sitzpläne',
            },
        ),
    ]
