# Generated by Django 6.0.1 on 2026-01-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anwesenheit', '0002_sitzplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitzplan',
            name='gang',
            field=models.IntegerField(default=2, verbose_name='Gang'),
        ),
    ]
