# Generated by Django 6.0.1 on 2026-02-01 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anwesenheit', '0004_remove_sitzplan_gang'),
        ('stammdaten', '0002_raum_gang_alter_raum_col_alter_raum_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitzplan',
            name='teilnehmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stammdaten.teilnehmer', verbose_name='Teilnehmer'),
        ),
    ]
