# Generated by Django 6.0.1 on 2026-07-09 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lehrplan', '0013_alter_ausbildungseinheit_time'),
        ('stammdaten', '0017_alter_abwesendma_daytime_alter_jourfixe_daytime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bewertung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(verbose_name='Note')),
                ('bewertung', models.CharField(max_length=50, verbose_name='Bewertung')),
            ],
            options={
                'verbose_name': 'Bewertung',
                'verbose_name_plural': 'Bewertungen',
            },
        ),
        migrations.CreateModel(
            name='IHK_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punkte', models.IntegerField(verbose_name='Punkte/Prozent')),
                ('note', models.FloatField(verbose_name='Note')),
            ],
            options={
                'verbose_name': 'IHK Notenschlüssel',
                'verbose_name_plural': 'IHK Notenschlüssel',
                'ordering': ['-punkte'],
            },
        ),
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=250, verbose_name='Thema intern')),
                ('inhalt', models.CharField(default='?', max_length=50, verbose_name='Überschrift')),
                ('frage', models.TextField(verbose_name='Frage')),
                ('musterantwort', models.TextField(default='', verbose_name='Musterantwort')),
                ('bild', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bild')),
                ('bildmuster', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bild Muster')),
                ('bildbreite', models.IntegerField(default=80, verbose_name='Bildbreite in %')),
                ('punkte', models.IntegerField(default=1, verbose_name='Erreichbare Punkte')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('thema', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lehrplan.ausbildungseinheit', verbose_name='Thema')),
            ],
            options={
                'verbose_name': 'Frage',
                'verbose_name_plural': 'Fragen',
                'ordering': ['thema', 'titel'],
            },
        ),
        migrations.CreateModel(
            name='Klausur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50, verbose_name='Überschrift')),
                ('thema', models.CharField(max_length=50, verbose_name='Thema')),
                ('termin', models.DateTimeField(verbose_name='termin')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('fragen', models.ManyToManyField(to='klausur.frage', verbose_name='Fragen')),
                ('gruppe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stammdaten.gruppe', verbose_name='Gruppe')),
            ],
            options={
                'verbose_name': 'Klausur',
                'verbose_name_plural': 'Klausuren',
                'ordering': ['gruppe', '-termin'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punkte', models.IntegerField(default=0, verbose_name='Punkte')),
                ('bemerkung', models.TextField(blank=True, null=True, verbose_name='Bemerkung')),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.teilnehmer', verbose_name='Teilnhmer*in')),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klausur.frage', verbose_name='Frage')),
                ('klausur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klausur.klausur', verbose_name='Klausur')),
            ],
            options={
                'verbose_name': 'Antwort',
                'verbose_name_plural': 'Antworten',
            },
        ),
        migrations.CreateModel(
            name='Klausurthema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=10, verbose_name='Position')),
                ('seitenwechsel', models.BooleanField(default=False, verbose_name='Seitenwechsel im Anschluss')),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='klausur.frage', verbose_name='Frage')),
                ('klausur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klausur.klausur', verbose_name='Klausur')),
            ],
            options={
                'verbose_name': 'Klausur-Thema',
                'verbose_name_plural': 'Klausur-Themen',
                'ordering': ['klausur', 'position'],
            },
        ),
    ]
