# Generated by Django 6.0.1 on 2026-03-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klausur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frage',
            options={'verbose_name': 'Frage', 'verbose_name_plural': 'Fragen'},
        ),
        migrations.AddField(
            model_name='frage',
            name='name',
            field=models.CharField(default='-', max_length=50, verbose_name='Titel'),
            preserve_default=False,
        ),
    ]
