# Generated by Django 4.2.7 on 2024-09-10 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('klausur', '0002_alter_teilnehmer_options_alter_thema_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klausur',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
            preserve_default=False,
        ),
    ]
