# Generated by Django 4.2.7 on 2024-10-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klausur', '0003_klausur_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klausurthema',
            name='position',
            field=models.IntegerField(default=10, verbose_name='Position'),
        ),
    ]
