# Generated by Django 5.1.1 on 2025-04-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klausur', '0006_alter_ihk_key_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ihk_key',
            options={'ordering': ['-punkte'], 'verbose_name': 'IHK Notenschlüssel', 'verbose_name_plural': 'IHK Notenschlüssel'},
        ),
    ]
