# Generated by Django 6.0.1 on 2026-03-21 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ueber', models.CharField(max_length=50, verbose_name='Aufgabe')),
                ('inhalt', models.TextField(verbose_name='Inhalt')),
                ('prio', models.IntegerField(verbose_name='Priorität')),
                ('termin', models.DateTimeField(blank=True, null=True, verbose_name='Termin')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('ersteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ersteller', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.aufgabe', verbose_name='Ursprungsaufgabe')),
                ('verantwortlich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responce', to=settings.AUTH_USER_MODEL, verbose_name='verantwortlich')),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
            },
        ),
    ]
