# Generated by Django 6.0.1 on 2026-03-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bereich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('beschreibung', models.TextField(verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Bereich',
                'verbose_name_plural': 'Bereichs',
            },
        ),
    ]
