# Generated by Django 6.0.1 on 2026-03-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_bereich'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bereich',
            options={'verbose_name': 'Bereich', 'verbose_name_plural': 'Bereiche'},
        ),
    ]
