# Generated by Django 6.0.1 on 2026-03-21 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_bereich_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='bereich',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.bereich', verbose_name=''),
            preserve_default=False,
        ),
    ]
