# Generated by Django 6.0.1 on 2026-03-21 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_aufgabe_bereich'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='aktuell',
            field=models.BooleanField(default=False, verbose_name='wird aktuell bearbeitet'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='bereich',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.bereich', verbose_name='Bereich'),
        ),
    ]
