# Generated by Django 6.0.1 on 2026-03-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_aufgabe_aktuell_alter_aufgabe_bereich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe',
            name='aktiv',
            field=models.BooleanField(default=True, verbose_name='Aktiv (offen)'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='prio',
            field=models.IntegerField(default=1, verbose_name='Priorität'),
        ),
    ]
