# Generated by Django 6.0.1 on 2026-03-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_aufgabe_aktiv_alter_aufgabe_prio'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='zyklisch',
            field=models.BooleanField(default=False, verbose_name='wiederholt sich die Aufgabe?'),
        ),
    ]
