# Generated by Django 6.0.1 on 2026-04-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_aufgabe_zyklisch'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='arch',
            field=models.BooleanField(default=False, verbose_name='Aufgabe archiviert?'),
        ),
    ]
