# Generated by Django 6.0.1 on 2026-02-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rahmenlehrplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Version von')),
                ('bereich', models.CharField(max_length=50, verbose_name='Bereich')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('bundesland', models.CharField(default='Baden-Württemberg', max_length=50, verbose_name='Beschreibung')),
                ('quelle', models.URLField(verbose_name='Quelle')),
                ('aktiv', models.BooleanField(default=True, verbose_name='aktiv')),
            ],
            options={
                'verbose_name': 'Rahmenlehrplan',
                'verbose_name_plural': 'Rahmenlehrpläne',
            },
        ),
    ]
