# Generated by Django 6.0.1 on 2026-02-26 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0001_initial'),
        ('stammdaten', '0013_alter_abwesendma_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lernfeld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=5, verbose_name='Nummer')),
                ('inhalt', models.CharField(max_length=200, verbose_name='Inhalt')),
                ('stunden1', models.IntegerField(default=0, verbose_name='Zeitrichtwerte 1. Jahr')),
                ('stunden2', models.IntegerField(default=0, verbose_name='Zeitrichtwerte 2. Jahr')),
                ('stunden3', models.IntegerField(default=0, verbose_name='Zeitrichtwerte 3. Jahr')),
                ('beschreibung', models.TextField(verbose_name='Beschreibung')),
                ('berufe', models.ManyToManyField(to='stammdaten.beruf', verbose_name='Berufe')),
                ('rahmenlehrplan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lehrplan.rahmenlehrplan', verbose_name='Rahmenlehrplan')),
            ],
            options={
                'verbose_name': 'Lernfeld',
                'verbose_name_plural': 'Lernfelder',
                'ordering': ['rahmenlehrplan', 'nummer'],
            },
        ),
    ]
