# Generated by Django 6.0.1 on 2026-02-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0002_lernfeld'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lernfeld',
            name='berufe',
        ),
    ]
