# Generated by Django 6.0.1 on 2026-03-02 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0003_remove_lernfeld_berufe'),
        ('stammdaten', '0013_alter_abwesendma_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fachrichtung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fachrichtung', models.CharField(max_length=50, verbose_name='Fachrichtung')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
            ],
            options={
                'verbose_name': 'Fachrichtung',
                'verbose_name_plural': 'Fachrichtungen',
            },
        ),
        migrations.AddField(
            model_name='lernfeld',
            name='berufe',
            field=models.ManyToManyField(to='stammdaten.beruf', verbose_name='Berufe'),
        ),
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thema', models.CharField(max_length=50, verbose_name='Thema')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('berufe', models.ManyToManyField(to='stammdaten.beruf', verbose_name='')),
                ('fachrichtung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lehrplan.fachrichtung', verbose_name='Fachrichtung')),
            ],
            options={
                'verbose_name': 'Thema',
                'verbose_name_plural': 'Themen',
            },
        ),
        migrations.CreateModel(
            name='Lerneinheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inhalt', models.CharField(max_length=50, verbose_name='Inhalt')),
                ('beschreibung', models.TextField(verbose_name='Beschreibung')),
                ('information', models.URLField(blank=True, null=True, verbose_name='Wiki-Link')),
                ('time', models.IntegerField(default=5, verbose_name='Anzahl Unterrichtseinheiten')),
                ('Ausbilder', models.ManyToManyField(to='stammdaten.ausbilder', verbose_name='Ausbilder')),
                ('lernfeld', models.ManyToManyField(to='lehrplan.lernfeld', verbose_name='entsprechende Lernfelder')),
                ('thema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lehrplan.thema', verbose_name='Thema')),
            ],
            options={
                'verbose_name': 'Lerneinheit',
                'verbose_name_plural': 'Lerneinheiten',
                'ordering': ['thema', 'inhalt'],
            },
        ),
    ]
