# Generated by Django 6.0.1 on 2026-03-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0004_fachrichtung_lernfeld_berufe_thema_lerneinheit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lerneinheit',
            name='lernfeld',
            field=models.ManyToManyField(blank=True, null=True, to='lehrplan.lernfeld', verbose_name='entsprechende Lernfelder'),
        ),
    ]
