# Generated by Django 6.0.1 on 2026-03-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0005_alter_lerneinheit_lernfeld'),
        ('stammdaten', '0013_alter_abwesendma_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lerneinheit',
            name='Ausbilder',
        ),
        migrations.AddField(
            model_name='lerneinheit',
            name='ausbilder',
            field=models.ManyToManyField(to='stammdaten.ausbilder', verbose_name='Ausbilder'),
        ),
    ]
