# Generated by Django 6.0.1 on 2026-03-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0006_remove_lerneinheit_ausbilder_lerneinheit_ausbilder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fachrichtung',
            options={'verbose_name': 'Fachrichtung', 'verbose_name_plural': 'LE_01_Fachrichtungen'},
        ),
        migrations.AlterModelOptions(
            name='lerneinheit',
            options={'ordering': ['thema', 'inhalt'], 'verbose_name': 'Lerneinheit', 'verbose_name_plural': 'LE_03_Lerneinheiten'},
        ),
        migrations.AlterModelOptions(
            name='lernfeld',
            options={'ordering': ['rahmenlehrplan', 'nummer'], 'verbose_name': 'Lernfeld', 'verbose_name_plural': 'RLP_02_Lernfelder'},
        ),
        migrations.AlterModelOptions(
            name='rahmenlehrplan',
            options={'verbose_name': 'Rahmenlehrplan', 'verbose_name_plural': 'RLP_01_Rahmenlehrpläne'},
        ),
        migrations.AlterModelOptions(
            name='thema',
            options={'verbose_name': 'Thema', 'verbose_name_plural': 'LE_02_Themen'},
        ),
        migrations.AddField(
            model_name='fachrichtung',
            name='short',
            field=models.CharField(default='-', max_length=5, verbose_name='Kürzel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thema',
            name='short',
            field=models.CharField(default='-', max_length=5, verbose_name='Kürzel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lerneinheit',
            name='lernfeld',
            field=models.ManyToManyField(blank=True, to='lehrplan.lernfeld', verbose_name='entsprechende Lernfelder'),
        ),
    ]
