# Generated by Django 6.0.1 on 2026-04-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0007_alter_fachrichtung_options_alter_lerneinheit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lernfeld',
            name='nummer',
            field=models.CharField(max_length=50, verbose_name='Nummer'),
        ),
    ]
