# Generated by Django 6.0.1 on 2026-04-21 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0008_alter_lernfeld_nummer'),
        ('stammdaten', '0017_alter_abwesendma_daytime_alter_jourfixe_daytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausbildungseinheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inhalt', models.CharField(max_length=50, verbose_name='Inhalt')),
                ('beschreibung', models.TextField(verbose_name='Beschreibung')),
                ('information', models.URLField(blank=True, null=True, verbose_name='Wiki-Link')),
                ('time', models.IntegerField(default=5, verbose_name='Anzahl Unterrichtseinheiten')),
                ('ausbilder', models.ManyToManyField(to='stammdaten.ausbilder', verbose_name='Ausbilder')),
                ('lernfeld', models.ManyToManyField(blank=True, to='lehrplan.lernfeld', verbose_name='entsprechende Lernfelder')),
                ('thema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lehrplan.ausbildungseinheit', verbose_name='Thema')),
            ],
            options={
                'verbose_name': 'Lerneinheit',
                'verbose_name_plural': 'LE_03_Lerneinheiten',
                'ordering': ['thema', 'inhalt'],
            },
        ),
    ]
