# Generated by Django 6.0.1 on 2026-04-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0009_ausbildungseinheit'),
        ('stammdaten', '0017_alter_abwesendma_daytime_alter_jourfixe_daytime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausbildungseinheit',
            options={'ordering': ['inhalt'], 'verbose_name': 'Lerneinheit', 'verbose_name_plural': 'LE_03_AE'},
        ),
        migrations.AlterField(
            model_name='ausbildungseinheit',
            name='ausbilder',
            field=models.ManyToManyField(blank=True, to='stammdaten.ausbilder', verbose_name='Ausbilder'),
        ),
    ]
