# Generated by Django 6.0.1 on 2026-05-28 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0010_alter_ausbildungseinheit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausbildungseinheit',
            options={'ordering': ['inhalt'], 'verbose_name': 'Ausbildungseinheit', 'verbose_name_plural': 'Ausbildungseinheiten'},
        ),
        migrations.AddField(
            model_name='ausbildungseinheit',
            name='voraussetzung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ab_req', to='lehrplan.ausbildungseinheit', verbose_name='Voraussetzung'),
        ),
        migrations.AlterField(
            model_name='ausbildungseinheit',
            name='beschreibung',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='ausbildungseinheit',
            name='thema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ab_thema', to='lehrplan.ausbildungseinheit', verbose_name='Thema'),
        ),
    ]
