# Generated by Django 6.0.1 on 2026-07-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0010_alter_ausbildungseinheit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausbildungseinheit',
            options={'ordering': ['inhalt'], 'verbose_name': 'Ausbildungseinheit', 'verbose_name_plural': 'Ausbildungseinheiten'},
        ),
    ]
