# Generated by Django 6.0.1 on 2026-07-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0011_alter_ausbildungseinheit_options'),
        ('lehrplan', '0011_alter_ausbildungseinheit_options_and_more'),
    ]

    operations = [
    ]
