# Generated by Django 6.0.1 on 2026-07-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0012_merge_20260709_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausbildungseinheit',
            name='time',
            field=models.IntegerField(default=0, verbose_name='Anzahl Unterrichtseinheiten'),
        ),
    ]
