# Generated by Django 6.0.1 on 2026-07-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0013_alter_ausbildungseinheit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lerneinheit',
            name='kuerzel',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Kürzel'),
        ),
        migrations.AlterField(
            model_name='lernfeld',
            name='stunden1',
            field=models.IntegerField(default=0, verbose_name='Zeitrichtwerte 1. Jahr / Reha'),
        ),
        migrations.AlterField(
            model_name='lernfeld',
            name='stunden2',
            field=models.IntegerField(default=0, verbose_name='Zeitrichtwerte 2. Jahr / FbW'),
        ),
        migrations.AlterField(
            model_name='lernfeld',
            name='stunden3',
            field=models.IntegerField(default=0, verbose_name='Zeitrichtwerte 3. Jahr / Digital'),
        ),
    ]
