# Generated by Django 6.0.1 on 2026-07-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0014_lerneinheit_kuerzel_alter_lernfeld_stunden1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lerneinheit',
            name='kuerzel',
        ),
        migrations.AddField(
            model_name='ausbildungseinheit',
            name='kuerzel',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Kürzel'),
        ),
    ]
