# Generated by Django 6.0.1 on 2026-07-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0015_remove_lerneinheit_kuerzel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausbildungseinheit',
            name='kuerzel',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Kürzel'),
        ),
    ]
